# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['-created'], 'verbose_name': 'party', 'verbose_name_plural': 'parties'},
        ),
    ]
