# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_year',
            field=models.PositiveIntegerField(default=2017),
        ),
    ]
