# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_auto_20170207_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='recurrence',
            field=models.IntegerField(choices=[(20, 'None'), (21, 'Daily'), (22, 'Weekly'), (23, 'Monthly')], default=20),
        ),
    ]
