# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_party_requesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='invite_type',
            field=models.IntegerField(choices=[(15, 'Open'), (16, 'Invite only')], default=15),
        ),
    ]
