# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_party_invite_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='party_year',
            field=models.PositiveIntegerField(default=2016),
        ),
    ]
