# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_party_party_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
    ]
