# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0008_auto_20160913_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
