# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 15:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[(b'1', 'flagged'), (b'2', 'flag rejected by moderator'), (b'3', 'creator notified'), (b'4', 'content removed by creator'), (b'5', 'content removed by moderator')], default=b'1', max_length=1)),
                ('count', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_content', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_content', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlagInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_added', models.DateTimeField(default=datetime.datetime.now)),
                ('when_recalled', models.DateTimeField(null=True)),
                ('comment', models.TextField()),
                ('flagged_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flag.FlaggedContent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='flaggedcontent',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
