# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flag', '0002_auto_20160113_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('flag_count', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.Party')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='flaggedcontent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='flaggedcontent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='flaggedcontent',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='flaggedcontent',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='flaginstance',
            name='flagged_content',
        ),
        migrations.RemoveField(
            model_name='flaginstance',
            name='user',
        ),
        migrations.DeleteModel(
            name='FlaggedContent',
        ),
        migrations.DeleteModel(
            name='FlagInstance',
        ),
    ]
