# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160818_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(default=1, max_length=100, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
