# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_blocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='times_flagged',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
