# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_myuser_times_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
