# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_myuser_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['user__full_name']},
        ),
    ]
