# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20161024_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-created']},
        ),
    ]
